# Generated by Django 5.1.4 on 2025-02-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistaccount',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
