# Generated by Django 5.1.4 on 2025-01-12 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=255)),
                ('music_genre', models.CharField(max_length=100)),
                ('music_date', models.DateField()),
                ('audio_file', models.FileField(upload_to='media/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artistaccount')),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
