# Generated by Django 5.1.4 on 2025-02-09 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_album_cover_image_alter_artistaccount_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artistaccount'),
            preserve_default=False,
        ),
    ]
