# Generated by Django 5.1.6 on 2025-02-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_remove_album_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artistaccount'),
            preserve_default=False,
        ),
    ]
