# Generated by Django 5.1.6 on 2025-02-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_playlist_musics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='musics',
        ),
    ]
