# Generated by Django 5.1.6 on 2025-02-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_remove_playlist_musics'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(to='musicapp.music'),
        ),
    ]
