# Generated by Django 5.1.6 on 2025-02-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_playlist_musics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='musics',
            new_name='music_set',
        ),
    ]
