# Generated by Django 5.1.4 on 2025-02-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_rename_musics_playlist_music_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
