# Generated by Django 5.1.6 on 2025-02-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0014_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
